In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
df = pd.read_csv("lista acoes.csv", delimiter=";")
df["ini"] = pd.to_datetime(df["ini"], format="%d/%m/%Y")
df["fim"] = pd.to_datetime(df["fim"], format="%d/%m/%Y")
df

         acao        ini        fim
0    VALE3.SA 2022-05-30 2022-08-01
1   KLBN11.SA 2022-05-30 2022-08-01
2    MOVI3.SA 2022-05-30 2022-08-01
3    PNVL3.SA 2022-05-30 2022-08-01
4    RRRP3.SA 2022-05-30 2022-08-01
5    TTEN3.SA 2022-05-30 2022-08-01
6    LAVV3.SA 2022-05-30 2022-08-01
7    ALSO3.SA 2022-05-30 2022-08-01
8    YDUQ3.SA 2022-05-30 2022-08-01
9    TUPY3.SA 2022-05-30 2022-08-01
10   MGLU3.SA 2022-05-30 2022-08-01
11   BBAS3.SA 2022-05-30 2022-08-01

In [3]:
df.set_index("acao", inplace=True)

In [4]:
df.index

Index(['VALE3.SA', 'KLBN11.SA', 'MOVI3.SA', 'PNVL3.SA', 'RRRP3.SA', 'TTEN3.SA',
       'LAVV3.SA', 'ALSO3.SA', 'YDUQ3.SA', 'TUPY3.SA', 'MGLU3.SA', 'BBAS3.SA'],
      dtype='object', name='acao')

In [5]:
cotacoes = pd.DataFrame()
for acao in df.index:
    ini = df.loc[acao,"ini"]
    fim = df.loc[acao,"fim"]
    print(acao, ini, fim)
    cotacoes[acao] = yf.download(acao, start=ini, end=fim)["Close"] # +".SA"
cotacoes

2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed
2022-05-30 00:00:00 2022-08-01 00:00:00
[*********************100%***********************]  1 of 1 completed

,VALE3.SA,KLBN11.SA,MOVI3.SA,PNVL3.SA,RRRP3.SA,TTEN3.SA,LAVV3.SA,ALSO3.SA,YDUQ3.SA,TUPY3.SA,MGLU3.SA,BBAS3.SA
Date,,,,,,,,,,,,
2022-05-30,86.650002,22.129999,17.660000,11.64,49.310001,9.41,5.28,19.219999,16.540001,22.420000,3.84,36.070000
2022-05-31,86.209999,22.270000,17.870001,11.53,48.750000,9.60,5.14,19.309999,16.180000,23.100000,3.72,36.619999
2022-06-01,88.239998,22.690001,18.059999,11.36,48.770000,9.75,5.13,18.660000,16.450001,23.469999,3.71,36.689999
2022-06-02,89.900002,22.750000,17.900000,11.48,48.560001,9.40,5.18,19.110001,16.650000,24.360001,3.80,36.720001
2022-06-03,88.459999,22.200001,16.870001,11.33,48.599998,9.36,5.18,18.920000,15.720000,24.379999,3.59,36.209999
2022-06-06,88.550003,22.240000,16.510000,10.99,46.860001,8.96,5.09,18.600000,15.170000,23.830000,3.40,35.759998
2022-06-07,90.620003,22.230000,16.549999,10.76,46.860001,8.92,5.00,18.459999,15.180000,23.219999,3.29,35.509998
2022-06-08,87.500000,21.940001,15.680000,10.67,46.790001,8.81,4.90,18.670000,14.920000,23.430000,3.22,35.189999
2022-06-09,84.540001,21.790001,15.940000,10.55,46.020000,8.83,4.98,18.290001,14.990000,23.590000,3.01,35.139999
2022-06-10,84.559998,21.360001,15.510000,10.28,44.570000,8.63,4.91,17.910000,14.250000,23.080000,2.90,34.549999
2022-06-13,81.879997,21.340000,14.520000,9.90,42.660000,8.48,4.74,17.270000,13.350000,22.320000,2.67,33.759998
2022-06-14,81.720001,20.920000,14.010000,9.78,40.840000,8.37,4.69,17.059999,13.470000,21.180000,2.54,33.520000
2022-06-15,81.669998,20.650000,14.280000,9.77,40.610001,8.27,4.80,17.540001,13.740000,21.750000,2.55,34.049999
2022-06-17,77.410004,20.360001,14.000000,9.62,36.750000,8.56,4.66,17.160000,13.330000,21.450001,2.38,34.130001
2022-06-20,75.500000,20.200001,14.180000,9.49,35.700001,8.41,4.62,16.940001,13.640000,21.030001,2.58,34.389999
2022-06-21,76.000000,20.100000,14.070000,9.36,36.400002,8.34,4.57,16.780001,13.170000,21.200001,2.51,32.980000
2022-06-22,75.349998,20.020000,13.940000,9.74,33.970001,8.35,4.55,16.910000,13.590000,21.290001,2.44,32.860001
2022-06-23,72.599998,19.520000,13.970000,9.89,32.799999,8.40,4.60,16.799999,13.750000,21.500000,2.55,32.650002
2022-06-24,74.620003,19.799999,13.660000,9.79,34.189999,8.10,4.60,16.719999,14.240000,21.520000,2.47,32.459999
2022-06-27,78.050003,20.150000,13.710000,9.67,36.380001,8.14,4.64,16.760000,13.960000,22.180000,2.43,33.130001
2022-06-28,79.449997,20.250000,13.680000,9.64,36.160000,8.00,4.66,16.430000,13.580000,22.790001,2.38,33.250000
2022-06-29,78.790001,20.160000,13.480000,9.46,35.900002,8.00,4.65,16.139999,13.400000,22.469999,2.41,33.080002
2022-06-30,76.559998,20.200001,13.050000,9.59,35.150002,8.00,4.62,16.010000,13.070000,22.230000,2.34,33.380001
2022-07-01,75.099998,20.190001,13.200000,9.32,35.590000,8.28,4.66,16.379999,12.980000,22.000000,2.20,33.150002
2022-07-04,74.669998,20.190001,12.900000,9.09,36.279999,8.29,4.54,16.450001,12.420000,21.500000,2.13,33.040001
2022-07-05,74.300003,19.799999,12.690000,9.43,33.580002,7.98,4.53,16.490000,12.610000,20.860001,2.38,32.860001
2022-07-06,75.000000,20.010000,12.850000,9.90,31.700001,8.16,4.54,16.420000,13.800000,20.850000,2.50,32.650002
2022-07-07,77.180000,19.900000,13.140000,10.17,31.900000,8.16,4.56,16.629999,15.250000,21.150000,2.56,33.130001
2022-07-08,75.400002,19.709999,12.880000,10.05,32.900002,8.11,4.51,16.809999,14.910000,21.049999,2.62,33.450001
2022-07-11,72.830002,19.510000,12.010000,10.06,32.369999,7.98,4.36,16.209999,14.280000,20.780001,2.63,32.900002
2022-07-12,73.050003,19.620001,11.890000,10.10,30.280001,7.90,4.35,16.450001,14.380000,20.850000,2.93,33.009998
2022-07-13,72.800003,19.040001,11.890000,10.05,28.600000,7.85,4.35,16.420000,13.890000,20.830000,2.83,32.650002
2022-07-14,67.949997,18.790001,12.200000,10.10,29.110001,7.97,4.30,16.040001,14.150000,20.600000,2.91,32.610001
2022-07-15,68.370003,18.500000,12.230000,10.20,28.740000,8.22,4.43,16.049999,14.720000,21.379999,2.78,33.279999
2022-07-18,68.730003,18.420000,12.120000,10.46,29.389999,8.31,4.39,16.070000,14.710000,21.400000,2.77,33.750000
2022-07-19,68.879997,18.799999,12.270000,10.11,30.440001,8.41,4.46,16.139999,14.120000,21.780001,2.79,34.660000
2022-07-20,67.389999,19.070000,12.500000,10.17,31.639999,8.67,4.57,16.379999,14.290000,22.000000,3.07,34.669998
2022-07-21,68.570000,18.459999,12.930000,10.35,30.450001,8.69,4.72,16.580000,14.090000,22.299999,3.01,34.910000
2022-07-22,69.209999,18.900000,12.770000,10.30,29.430000,8.83,4.60,16.680000,13.900000,22.090000,2.86,34.669998
2022-07-25,70.489998,18.420000,12.780000,10.33,30.260000,8.81,4.46,16.639999,13.540000,22.150000,2.79,35.200001
2022-07-26,70.360001,18.450001,12.400000,10.26,29.940001,8.82,4.46,16.370001,12.910000,21.790001,2.61,35.320000
2022-07-27,70.519997,19.459999,12.770000,10.47,30.670000,9.14,4.62,16.870001,13.840000,22.270000,2.70,35.549999
2022-07-28,70.690002,19.230000,12.900000,11.06,31.830000,9.12,4.88,17.070000,13.530000,22.389999,2.72,36.209999
2022-07-29,69.750000,19.930000,12.700000,10.98,34.020000,9.18,4.86,16.870001,13.250000,22.770000,2.58,35.970001

In [6]:
cotacoes.to_excel("./data/cotacoes.xlsx")